export type ClientStatus = "Active" | "On Hold";

export type ProjectStatus = "Active" | "On Hold";

export type TaskPriority = "High" | "Medium" | "Low";

export type TaskStatus = "To Do" | "In Progress" | "Review" | "Blocked" | "Done";

export type ContactStatus = "Active" | "Inactive";

/**
 * Formats an ISO calendar date (`YYYY-MM-DD`) for Task list/detail display.
 * Persistence and the API always use ISO; this is UI-only.
 */
export function formatTaskDueDate(isoDate: string): string {
  const [year, month, day] = isoDate.split("-").map(Number);

  if (!year || !month || !day) {
    return isoDate;
  }

  const date = new Date(year, month - 1, day);

  return date.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
  });
}

export function formatContactName(firstName: string, lastName: string): string {
  return `${firstName} ${lastName}`;
}

/**
 * Contact slugs are generated by the server, so there is deliberately no client-side
 * equivalent of a contact slug helper here.
 */
export function resolveClientPrimaryContact<T extends { id: string }>(
  client: { primaryContactId: string | null },
  contacts: T[],
): T | undefined {
  if (!client.primaryContactId) {
    return undefined;
  }

  return contacts.find((contact) => contact.id === client.primaryContactId);
}
